= Matrix sample apps
Paulo Jerônimo <paulojeronimo@gmail.com>, {localdatetime}
:toc:
:toclevels: 4
:icons: font
:numbered:

== Turn the Matrix functions available in your shell

----
$ source ../functions.sh
----

. The line above will turn available the `matrix-*` functions in your
shell.
You can see what are these functions by typing the following command:
+
----
$ set | grep ^matrix-
----
+
. It will also put a line inside your `~/.bashrc` or `~./bash_profile`
  (depend on with OS you are using) with will automatically load this
script for you. You can check this by running the following command:
+
----
$ grep functions ~/.bash_profile
----

== Start the Matrix

----
$ matrix-create
----

. You can now open http://localhost:8080/auth/admin/ and log in using
the credentials configured in `../config.sh`. The credentails are
configured by two shell variables: `MATRIX_ADMIN_USER` and
`MATRIX_ADMIN_PASSWORD`.
.. The `../config.sh` is a copy of the file link:../config.sample.sh[]
with your own configurations (and it is ignored by Git).
. The `matrix-create` function will start a Keycloak docker container.
This container will be an instance of the image configured in the file
`../config.sh`. The docker image (and the created container) can be
checked by the following commands:
+
----
$ docker images | grep keycloak
$ docker container ls | grep keycloak
----

== Run the sample apps

=== Plain JavaScript

==== Starting and configuring Keycloak

----
$ cd plain-js
$ matrix-project-add
----
. The `matrix-project-add` function will add the current project.
.. A project is a directory containing a file called
`matrix-functions.sh`.
The function with suffix `-project-add` (inside this file) will be
called automatically.

==== Starting the webapp

----
$ ./serve.sh &
----

. This will start a local server listening on port 3000 and serving the
  directory link:plain-js/webapp[] which contains an static
HTML file called `index.html`.

----
$ open http://localhost:3000
----

. You will need to register an new user. After that you will be
  automatically redirected to the app, as a logged user.

==== References

* https://www.keycloak.org/docs/latest/securing_apps/#_javascript_adapter

=== React

=== Spring Boot

